all: build sim
compile:
	@echo "No compile needed"
build:
	@echo "No build needed"
sim:
	cd /home/ubuntu/LineFollower_Success && PYTHONPATH=. python3 src/visualizer/visualizer.py --domain=AF_INET --server-url=localhost --label=$(LABEL); bash
clean:
	@echo "Nothing to clean"
