all: build sim
compile:
	@echo "No compile needed"
build:
	@echo "No build needed"
sim:
	cd /home/ubuntu/LineFollower_Success && PYTHONPATH=. python3 src/plant/plant.py --domain=AF_INET --server-url=localhost; bash
clean:
	@echo "Nothing to clean"
